#!/bin/bash
#SBATCH --job-name=singleCurrentTest
#SBATCH --time=10:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=14
#SBATCH --mem=6G

#SBATCH --mail-type=ALL
#SBATCH --mail-user=m0908394@tamu.edu

module purge
module load Tcl/8.6.11-GCCcore-10.3.0   Tk/8.6.11-GCCcore-10.3.0
tclsh /scratch/user/m0908394/Oommf/oommf/oommf.tcl boxsi -parameters "max_current 35" -threads 14 /scratch/user/m0908394/Oommf/oommf/Skyrmion/skyrmionDomeTransport2.mif